//api1
POST http://localhost:3000/register/
Content-Type: application/json

{
  "userName": "adam_richard1",
  "password": "rich5",
  "name": "Adam Richard",
  "gender":"male"
}


//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo
//api2 //login 
### 
POST http://localhost:3000/login/
Content-Type: application/json

{
   "username":"JoeBiden",
  "password":"biden@123"
}

###
//api3 
GET  http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo

### 
//api4 
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo

###
//api5 
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo

###
//api 6
GET http://localhost:3000/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo


###
//api 7
GET http://localhost:3000/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo


### 
//api 8
GET http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo

###
//api 9
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo


###
//api 10
POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo
Content-Type: application/json

{
   "tweet": "The Mornings vivek reddy..."

}


###
//api 11
DELETE http://localhost:3000/tweets/15/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjIwNzI3MDkyfQ.Podi50samA8uiUkFcGEs-1snciS4tC-PCUo7WnVs4xo
